services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $botToken: '%env(TELEGRAM_BOT_TOKEN)%'
            $botUsername: '%env(TELEGRAM_BOT_USERNAME)%'

    Morfeditorial\MachinimaBotBundle\Screens\:
        resource: '../../Screens/'
        public: true

    Morfeditorial\MachinimaBotBundle\Commands\:
        resource: '../../Commands/'
        public: true

    Morfeditorial\MachinimaBotBundle\Service\:
        resource: '../../Service/'
        public: true

    Morfeditorial\MachinimaBotBundle\Twig\BotLinkExtension:
        tags:
            - 'twig.extension'

    Morfeditorial\MachinimaBotBundle\Translator:
        public: true

    bot_translator:
        alias: Morfeditorial\MachinimaBotBundle\Translator
        public: true
