services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $botToken: '%env(TELEGRAM_BOT_TOKEN)%'

    Morfeditorial\Screens\:
        resource: '../../Screens/'
        public: true

    Morfeditorial\Commands\:
        resource: '../../Commands/'
        public: true

    Morfeditorial\Service\:
        resource: '../../Service/'
        public: true

    Morfeditorial\Translator:
        public: true

    bot_translator:
        alias: Morfeditorial\Translator
        public: true
